---
scenario:
  name: ubuntu-18.04
platforms:
  - name: ubuntu-18.04
    groups:
      - nomad_instances
    image: monolithprojects/systemd-ubuntu18:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes

