---
scenario:
  name: debian-10
platforms:
  - name: debian-10
    groups:
      - nomad_instances
    image: dokken/debian-10
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
